'on':
  github:
    branches: ['temp_workflow']
    paths: ['code/**']
jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
      # url: https://github.com/GhaidaAlAtoum/test_gradient_workflow.git