run_config:
    general:
        batch_size: 64
        # output_dir: "./outputs"
        output_dir: "./outputs/training-output-dataset"
    train_dataset:
        fair_face_path: "/inputs/fair-face-volume/fairface"
        # fair_face_path: "/notebooks/data/fairface/"
        overwrite_sample_number: false
        number_samples: 100
    train_config:
        num_epochs: 100
        early_stopping_patience: 10
        checkpoint_frequencey: 5
model_config:
    model_name: "model_8conv_5kernel_with_flat"
    conv_blocks:
        block_1:
            num_conv_layers: 2
            num_filters: 64
            kernel_size: 5
        block_2:
            num_conv_layers: 2
            num_filters: 64
            kernel_size: 5
        block_3:
            num_conv_layers: 2
            num_filters: 64
            kernel_size: 5
        block_4:
            num_conv_layers: 2
            num_filters: 64
            kernel_size: 5
    flatt_layers:
        flat_1:
            num_units: 2048
        flat_2:
            num_units: 2048